books/phoenix-in-action/auction-umbrella/apps/auction_web/lib/auction_web/router.ex
defmodule AuctionWeb.Router do
    use AuctionWeb, :router

    pipeline :browser do
        plug :accepts, ["html"]
        plug :fetch_session
        plug :fetch_live_flash
        plug :put_root_layout, {AuctionWeb.LayoutView, :root}
        plug :protect_from_forgery
        plug :put_secure_browser_headers
        plug AuctionWeb.Authenticator
    end

    pipeline :api do
        plug :accepts, ["json"]
    end

    scope "/", AuctionWeb do
        pipe_through :browser

        get "/", PageController, :index

        # These routes are the default ones that are created with resources
        # get    "/items",          ItemsController, :index
        # get    "/items/new",      ItemsController, :new
        # post   "/items",          ItemsController, :create
        # get    "/items/:id",      ItemsController, :show
        # get    "/items/:id/edit", ItemsController, :edit
        # patch  "/items/:id",      ItemsController, :update
        # put    "/items/:id",      ItemsController, :update
        # delete "/items/:id",      ItemsController, :delete
        resources "/items", ItemsController, 
             only: [:index, :show, :new, :create, :edit, :update] 
        do
            # Nested routes <BASE_URL>/items/123/bids
            resources "/bids",  BidsController,  only: [:create]
        end

        resources "/users", UsersController, only: [:show, :new, :create]


        get    "/signin",  SessionController, :new
        post   "/signin",  SessionController, :create
        delete "/signout", SessionController, :delete
    end

    # Other scopes may use custom stacks.
    # scope "/api", AuctionWeb do
    #   pipe_through :api
    # end

    # Enables LiveDashboard only for development
    #
    # If you want to use the LiveDashboard in production, you should put
    # it behind authentication and allow only admins to access it.
    # If your application does not have an admins-only section yet,
    # you can use Plug.BasicAuth to set up some basic authentication
    # as long as you are also using SSL (which you should anyway).
    if Mix.env() in [:dev, :test] do
        import Phoenix.LiveDashboard.Router

        scope "/" do
            pipe_through :browser
            live_dashboard "/dashboard", metrics: AuctionWeb.Telemetry
        end
    end

    # Enables the Swoosh mailbox preview in development.
    #
    # Note that preview only shows emails that were sent by the same
    # node running the Phoenix server.
    if Mix.env() == :dev do
        scope "/dev" do
            pipe_through :browser

            forward "/mailbox", Plug.Swoosh.MailboxPreview
        end
    end
end

books/phoenix-in-action/auction-umbrella/apps/auction_web/lib/auction_web/views/layout_view.ex
defmodule AuctionWeb.LayoutView do
  use AuctionWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

books/phoenix-in-action/auction-umbrella/apps/auction_web/lib/auction_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

books/phoenix-in-action/auction-umbrella/apps/auction_web/lib/auction_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

books/phoenix-in-action/auction-umbrella/apps/auction_web/lib/auction_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "AuctionWeb", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <div class="container" style="border-bottom: 1px solid #777; 
                                  margin-bottom: 2rem; 
                                  padding-bottom: 1rem;">
        <%= link "Items", to: Routes.items_path(@conn, :index) %>
        <%= if @current_user do %>
            Signed In as <%= link @current_user.username, to: Routes.users_path(@conn, :show, @current_user) %>
            <%= link "Sign Out", to: Routes.session_path(@conn, :delete), method: :delete %>
        <% else %>
            <%= link "Sign In", to: Routes.session_path(@conn, :new) %>
        <% end %>
    </div>
    <%= @inner_content %>
  </body>
</html>