books/phoenix-in-action/auction-umbrella/apps/auction_web/lib/auction_web/router.ex
defmodule AuctionWeb.Router do
    use AuctionWeb, :router

    pipeline :browser do
        plug :accepts, ["html"]
        plug :fetch_session
        plug :fetch_live_flash
        plug :put_root_layout, {AuctionWeb.LayoutView, :root}
        plug :protect_from_forgery
        plug :put_secure_browser_headers
        plug AuctionWeb.Authenticator
    end

    pipeline :api do
        plug :accepts, ["json"]
    end

    scope "/", AuctionWeb do
        pipe_through :browser

        get "/", PageController, :index

        # These routes are the default ones that are created with resources
        # get    "/items",          ItemsController, :index
        # get    "/items/new",      ItemsController, :new
        # post   "/items",          ItemsController, :create
        # get    "/items/:id",      ItemsController, :show
        # get    "/items/:id/edit", ItemsController, :edit
        # patch  "/items/:id",      ItemsController, :update
        # put    "/items/:id",      ItemsController, :update
        # delete "/items/:id",      ItemsController, :delete
        resources "/items", ItemsController, 
             only: [:index, :show, :new, :create, :edit, :update] 
        do
            # Nested routes <BASE_URL>/items/123/bids
            resources "/bids",  BidsController,  only: [:create]
        end

        resources "/users", UsersController, only: [:show, :new, :create]


        get    "/signin",  SessionController, :new
        post   "/signin",  SessionController, :create
        delete "/signout", SessionController, :delete
    end

    # Other scopes may use custom stacks.
    # scope "/api", AuctionWeb do
    #   pipe_through :api
    # end

    # Enables LiveDashboard only for development
    #
    # If you want to use the LiveDashboard in production, you should put
    # it behind authentication and allow only admins to access it.
    # If your application does not have an admins-only section yet,
    # you can use Plug.BasicAuth to set up some basic authentication
    # as long as you are also using SSL (which you should anyway).
    if Mix.env() in [:dev, :test] do
        import Phoenix.LiveDashboard.Router

        scope "/" do
            pipe_through :browser
            live_dashboard "/dashboard", metrics: AuctionWeb.Telemetry
        end
    end

    # Enables the Swoosh mailbox preview in development.
    #
    # Note that preview only shows emails that were sent by the same
    # node running the Phoenix server.
    if Mix.env() == :dev do
        scope "/dev" do
            pipe_through :browser

            forward "/mailbox", Plug.Swoosh.MailboxPreview
        end
    end
end

books/phoenix-in-action/auction-umbrella/apps/auction_web/lib/auction_web/controllers/items_controller.ex
defmodule AuctionWeb.ItemsController do
    use AuctionWeb, :controller

    def index(conn, _params) do
        items = Auction.list_items()
        render(conn, "index.html", items: items)
    end

    def show(conn, %{ "id" => id }) do
        item = Auction.get_item(id)
        bid = Auction.new_bid()
        render(conn, "show.html", item: item, bid: bid)
    end

    def new(conn, _params) do
        item = Auction.new_item()
        render(conn, "new.html", item: item)
    end

    def create(conn, %{ "item" => item_params }) do
        case Auction.insert_item(item_params) do
            { :ok,    item } -> redirect(conn, to: Routes.items_path(conn, :show, item))
            { :error, item } -> render(conn, "new.html", item: item)
        end
    end

    def edit(conn, %{ "id" => id }) do
        item = Auction.edit_item(id)
        render(conn, "edit.html", item: item)
    end

    def update(conn, %{ "id" => id, "item" => updates }) do
        item = Auction.get_item(id)
        case Auction.update_item(item, updates) do
            { :ok,    item } -> redirect(conn, to: Routes.items_path(conn, :show, item))
            { :error, item } -> render(conn, "edit.html", item: item)
        end
    end
end

books/phoenix-in-action/auction-umbrella/apps/auction_web/lib/auction_web/views/items_view.ex
defmodule AuctionWeb.ItemsView do
    use AuctionWeb, :view
end

books/phoenix-in-action/auction-umbrella/apps/auction_web/lib/auction_web/templates/items/edit.html.eex
<style>
  .form-group {
      margin-bottom: 10px;
  }
</style>

<h1>Edit Item</h1>

<%= form_for @item, Routes.items_path(@conn, :update, @item.data), fn x -> %>
  <%= if @item.action do %>
    <div class="alert alert-dangerous">
      Unfortunately, there are errors in your submission. Please correct them bellow.
    </div>
  <% end %>

  <div class="form-group">
    <%= label(x, :title) %>
    <%= text_input(x, :title) %>
    <%= error_tag(x, :title) %>
  </div>

  <div class="form-group">
    <%= label(x, :description) %>
    <%= text_input(x, :description) %>
    <%= error_tag(x, :description) %>
  </div>

  <div class="form-group">
    <%= label(x, :ends_at, "Auction ends at") %>
    <%= datetime_select(x, :ends_at) %>
    <%= error_tag(x, :ends_at) %>
  </div>

    <%= submit("Submit") %>
  </div>
<% end %>

books/phoenix-in-action/auction-umbrella/apps/auction_web/lib/auction_web/templates/items/index.html.eex
<ul>
    <%= for item <- @items do %>
        <li>
            <a href="http://127.0.0.1:4000/items/<%= item.id %>">
                <strong><%= item.title %>:</strong>
            </a>
            <%= item.description %>
        </li>

        <!-- <li> -->
        <!--     <strong> -->
        <!--         <%= link(item.title, to: Routes.items_path(@conn, :show, item)) %> -->
        <!--     </strong> -->
        <!--     <%= item.description %> -->
        <!-- </li> -->
    <% end %>
</ul>

books/phoenix-in-action/auction-umbrella/apps/auction_web/lib/auction_web/templates/items/new.html.eex
<style>
  .form-group {
      margin-bottom: 10px;
  }
</style>

<h1>New Item</h1>

<%= form_for @item, Routes.items_path(@conn, :create), fn x -> %>
  <%= if @item.action do %>
    <div class="alert alert-dangerous">
      Unfortunately, there are errors in your submission. Please correct them bellow.
    </div>
  <% end %>

  <div class="form-group">
    <%= label(x, :title) %>
    <%= text_input(x, :title) %>
    <%= error_tag(x, :title) %>
  </div>

  <div class="form-group">
    <%= label(x, :description) %>
    <%= text_input(x, :description) %>
    <%= error_tag(x, :description) %>
  </div>

  <div class="form-group">
    <%= label(x, :ends_at, "Auction ends at") %>
    <%= datetime_select(x, :ends_at) %>
    <%= error_tag(x, :ends_at) %>
  </div>

    <%= submit("Submit") %>
  </div>
<% end %>

books/phoenix-in-action/auction-umbrella/apps/auction_web/lib/auction_web/templates/items/show.html.eex
<h1><%= @item.title %></h1>

<ul>
    <li><strong>Description:</strong> <%= @item.description %></li>
    <li><strong>Auction ends at:</strong> <%= @item.ends_at %></li>
</ul>

<%= if @current_user do %>
    <h2>Place your bid</h2>

    <%= form_for @bid, Routes.items_bids_path(@conn, :create, @item), fn form -> %>

        <%= if @bid.action do %>
            <div class="alert alert-danger">
                Unfornately, there are errors in your submission.
                Please correct them bellow.
            </div>
        <% end %>

        <div class="form-group">
            <%= label(form, :amount, "Bid amount", class: "control-label") %>
            <%= error_tag(form, :amount)%>
            <%= number_input(form, :amount, class: "form-control") %>
        </div>


        <%= submit("Submit", class: "btn btn-primary") %>
    <% end %>
<% end %>